# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: pvanderl <pvanderl@student.s19.be>         +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2018/08/26 12:15:01 by pvanderl          #+#    #+#              #
#    Updated: 2018/08/26 13:49:53 by pvanderl         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = do-op
RES = ./*.c

all:
	gcc -Wextra -Werror -Wall -o $(NAME) $(RES)

clean:
	rm $(NAME)

re: clean all
